# -*- coding: utf-8 -*-

# --------------------------------------
# classe ListeDArret
# --------------------------------------
class ListeDArret:

    mots = "un \
            une \
            les \
            de \
            le \
            il \
            à \
            l \
            d \
            des \
            que \
            en \
            qui \
            dans \
            se \
            elle \
            qu \
            s \
            du \
            sur \
            vous \
            était \
            son \
            lui \
            au \
            pas \
            pour \
            avait \
            ce \
            ne \
            je \
            sa \
            avec \
            on \
            plus \
            comme \
            par \
            la \
            et \
            est \
            mais \
            tout \
            ses \
            artagnan \
            dit \
            deux \
            c \
            cette \
            n \
            m \
            si \
            ils \
            même \
            sans \
            a \
            où \
            nous \
            tous \
            y \
            dont \
            aux \
            ces \
            là \
            quand \
            encore \
            ça \
            autres \
            autre \
            leur \
            puis \
            étaient \
            trois \
            leurs \
            toutes \
            donc \
            très \
            ni \
            alors \
            enfin \
            tu \
            j' \
            j \
            me \
            ai \
            t \
            ainsi \
            lorsque \
            faisait \
            car \
            te \
            "